AWSTemplateFormatVersion: '2010-09-09'
Description: Basic CloudFormation Template

Parameters:
    EnvironmentName:
        Type: String
        Default: JuiceShop
        Description: A Vunrelible Web Application for Security Training
    
    InstanceType:
        Type: String
        Default: t3.micro
        Description: EC2 Instance Type
        AllowedValues:
            - t3.nano
            - t3.micro
            - t3a.micro
            - t4g.micro
        ConstraintDescription: must be a valid EC2 instance type.
    
    KeyName:
        Type: AWS::EC2::KeyPair::KeyName
        Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    

    

Resources:
    MyVPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 10.0.3.0/26
            EnableDnsHostnames: true
            EnableDnsSupport: true
            Tags:
                - Key: Name
                  Value: !Sub ${EnvironmentName}-VPC
    MyInternetGateway:
        Type: AWS::EC2::InternetGateway
        Properties:
            Tags:
                - Key: Name
                  Value: !Sub ${EnvironmentName}-IG

    MyVPCGatewayAttachment:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
            VpcId: !Ref MyVPC
            InternetGatewayId: !Ref MyInternetGateway
            
    MyVPCSubnet1:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref MyVPC
            CidrBlock: 10.0.3.0/28
            AvailabilityZone: !Select [ 0, !GetAZs '' ]

            MapPublicIpOnLaunch: true
            Tags:
                - Key: Name
                  Value: !Sub ${EnvironmentName}-Subnet1
    
    MyVPCSubnet2:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref MyVPC
            CidrBlock: 10.0.3.16/28
            AvailabilityZone: !Select [ 1, !GetAZs '' ]
            MapPublicIpOnLaunch: true
            Tags:
                - Key: Name
                  Value: !Sub ${EnvironmentName}-Subnet2

    MyRouteTable:
        Type: AWS::EC2::RouteTable
        Properties:
            VpcId: !Ref MyVPC 
            Tags: 
                - Key: Name
                  Value: !Sub ${EnvironmentName}-RouteTable

    MyInternetRoute:
        Type: AWS::EC2::Route
        Properties:
            RouteTableId: !Ref MyRouteTable
            DestinationCidrBlock: 0.0.0.0/0
            GatewayId: !Ref MyInternetGateway


    MySubnetAssociation1:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref MyRouteTable
            SubnetId: !Ref MyVPCSubnet1
            
    MySubnetAssociation2:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref MyRouteTable
            SubnetId: !Ref MyVPCSubnet2

    MyLbSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allow HTTP and HTTPS from everywhere
            VpcId: !Ref MyVPC
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 80
                  ToPort: 80
                  CidrIp: 0.0.0.0/0
                - IpProtocol: tcp
                  FromPort: 443
                  ToPort: 443
                  CidrIp: 0.0.0.0/0
            Tags:
                - Key: Name
                  Value: !Sub ${EnvironmentName}-LB-SG
                      
    MyServerSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allow HTTP and HTTPS from Load Balancer
            VpcId: !Ref MyVPC
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 80
                  ToPort: 80
                  SourceSecurityGroupId: !Ref MyLbSecurityGroup
                
                - IpProtocol: tcp
                  FromPort: 443
                  ToPort: 443
                  SourceSecurityGroupId: !Ref MyLbSecurityGroup

            Tags:
                - Key: Name
                  Value: !Sub ${EnvironmentName}-Server-SG

    
    MyS3Bucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketEncryption:
                ServerSideEncryptionConfiguration:
                    - ServerSideEncryptionByDefault:
                        SSEAlgorithm: AES256
            PublicAccessBlockConfiguration:
                BlockPublicAcls: true
                BlockPublicPolicy: true
                IgnorePublicAcls: true
                RestrictPublicBuckets: true
            Tags:
                - Key: Name
                  Value: !Sub ${EnvironmentName}-S3-Bucket

    MyVulnerableRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                        Service: "ec2.amazonaws.com"
                      Action: 'sts:AssumeRole'
            Policies:
                - PolicyName: S3policy
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                        - Effect: Allow
                          Action:
                            - s3:GetObject
                            - s3:ListBucket
                          Resource: 
                            - !GetAtt MyS3Bucket.Arn
                            - !Sub ${MyS3Bucket.Arn}/*
            Tags:
                - Key: Name
                  Value: !Sub ${EnvironmentName}-Vulnerable-Role


    MyInstanceProfile:
        Type: AWS::IAM::InstanceProfile
        Properties:
            Roles:
                - !Ref MyVulnerableRole

    
    MyinstanceTargetgroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            Port: 80
            Protocol: HTTP
            VpcId: !Ref MyVPC
            TargetType: instance
            HealthCheckPath: /
            Tags:
                - Key: Name
                  Value: !Sub ${EnvironmentName}-Target-Group
    MyLoadBalancer:
        Type: AWS::ElasticLoadBalancingV2::LoadBalancer
        Properties:
            Scheme: internet-facing
            Subnets:
                - !Ref MyVPCSubnet1
                - !Ref MyVPCSubnet2
            SecurityGroups: 
                - !Ref MyLbSecurityGroup
            Tags:
                - Key: Name
                  Value: !Sub ${EnvironmentName}-Load-Balancer
    MyListener:
        Type: AWS::ElasticLoadBalancingV2::Listener
        Properties:
            LoadBalancerArn: !Ref MyLoadBalancer
            DefaultActions: 
                - Type: forward
                  TargetGroupArn: !Ref MyinstanceTargetgroup
            Port: 80
            Protocol: HTTP
           
           
    MyLaunchTemplate:
        Type: AWS::EC2::LaunchTemplate
        Metadata:
            AWS::CloudFormation::Init:
                configSets:
                    default:
                        - CfnHupInstall
                CfnHupInstall:
                    file:
                        /etc/cfn/cfn-hup.conf:
                            content: !Sub |
                                [main]
                                stack=${AWS::StackName}
                                region=${AWS::Region}
                            mode: '000400'
                            owner: root
                            group: root
                        /etc/cfn/hooks.d/cfn-auto-reloader.conf:
                            content: !Sub |
                                [cfn-auto-reloader-hook]
                                triggers=post.update
                                path=Resources.MyLaunchTemplate.Metadata.AWS::CloudFormation::Init
                                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource MyLaunchTemplate --region ${AWS::Region}
                                runas=root
                            mode: '000400'
                            owner: root
                            group: root
                        /etc/systemd/system/cfn-hup.service:
                            content: !Sub |
                                [Unit]
                                Description=CloudFormation HUP daemon
                                After=network.target

                                [Service]
                                Type=simple
                                ExecStart=/opt/aws/bin/cfn-hup -f /etc/cfn/cfn-hup.conf -s
                                Restart=always
                                RestartSec=10

                                [Install]
                                WantedBy=multi-user.target
                           
                        /etc/systemd/system/juice-shop.service:
                            content: !Sub |
                                [Unit]
                                Description=Juice Shop Service
                                After=network.target

                                [Service]
                                Type=simple
                                User=juicer
                                WorkingDirectory=/juice-shop
                                ExecStart=/usr/bin/npm start
                                Restart=always
                                RestartSec=10

                                [Install]
                                WantedBy=multi-user.target
                        /etc/nginx/sites-available/juice-shop:
                            content: |
                                server {
                                    listen 80;
                                    server_name localhost;

                                    location / {
                                        proxy_pass http://localhost:3000;
                                        proxy_http_version 1.1;
                                        proxy_set_header Upgrade $http_upgrade;
                                        proxy_set_header Connection 'upgrade';
                                        proxy_set_header Host $host;
                                        proxy_cache_bypass $http_upgrade;
                                    }
                                }

                        commands:
                            01_install_cfn_hup:
                                command: |
                                    set -xe
                                    systemctl enable cfn-hup
                                    systemctl start cfn-hup
                          
        Properties:
            LaunchTemplateName: MyJuiceShop-template
            LaunchTemplateData:
                ImageId:  resolve:ssm:/aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id
                InstanceType: !Ref InstanceType
                KeyName: !Ref KeyName
                SecurityGroupIds:
                    - !Ref MyServerSecurityGroup
                IamInstanceProfile: 
                    Name: !Ref MyInstanceProfile
                UserData: 
                    Fn::Base64: !Sub | 
                        #!/bin/bash
                        apt-get update -y
                        apt-get -y purge unattended-upgrades
                        curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
                        apt-get -y install curl dirmngr apt-transport-https lsb-release ca-certificates python-setuptools awscli nodejs gcc g++ make nginx

                        addgroup --system --gid 1033 juicer
                        adduser --system --uid 1033 --gid juicer --ingroup juicer --home /home/juicer --shell /bin/bash juicer
                        
                        git clone https://github.com/juice-shop/juice-shop.git /var/www/juice-shop         
                        cd /var/www/juice-shop
                        
                        npm install --unsafe-perm

                        npm install -g pm2
                        pm2 start app.js --name "juice-shop"
                        pm2 save

                        /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource MyAutoScalingGroup --region ${AWS::Region}















    MyAutoScalingGroup:
        Type: AWS::AutoScaling::AutoScalingGroup
        CreationPolicy:
            ResourceSignal:
                Timeout: PT15M
        Properties:
            MinSize: 1
            MaxSize: 3
            LaunchTemplate: 
                LaunchTemplateId: !Ref MyLaunchTemplate
                Version: !GetAtt MyLaunchTemplate.LatestVersionNumber
            HealthCheckType: ELB
            HealthCheckGracePeriod: 300
            TargetGroupARNs:
                - !Ref MyinstanceTargetgroup
            VPCZoneIdentifier:
                - !Ref MyVPCSubnet1
                - !Ref MyVPCSubnet2
            Tags:
                - Key: Name
                  PropagateAtLaunch: true 
                  Value: !Sub ${EnvironmentName}-Auto-Scaling-Group




Outputs:
    LoadBalancerDNS:
        Description: the URL of the Load Balancer
        Value: !GetAtt MyLoadBalancer.DNSName

