AWSTemplateFormatVersion: '2010-09-09'
Description: Basic CloudFormation Template

Parameters:
    EnvironmentName:
        Type: String
        Default: JuiceShop
        Description: A Vunrelible Web Application for Security Training
    
    InstanceType:
        Type: String
        Default: t3.micro
        Description: EC2 Instance Type
        AllowedValues:
            - t2.nano
            - t3.micro
            - t3a.micro
            - t4g.micro
        ConstraintDescription: must be a valid EC2 instance type.
    
    KeyName:
        Type: AWS::EC2::KeyPair::KeyName
        Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    

    

Resources:
    MyVPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 10.0.3.0/26
            EnableDnsHostnames: true
            EnableDnsSupport: true
            Tags:
                - Key: Name
                  Value: MyJuiceShop-VPC
    MyInternetGateway:
        Type: AWS::EC2::InternetGateway
        Properties:
            Tags:
                - Key: Name
                  Value: Juiceshop-IG

    MyVPCGatewayAttachment:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
            VpcId: !Ref MyVPC
            InternetGatewayId: !Ref MyInternetGateway

    MyVPCSubnet1:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref MyVPC
            CidrBlock: 10.0.3.0/28
            AvailabilityZone: !Select [ 0, !GetAZs '' ]

            MapPublicIpOnLaunch: true
            Tags:
                - Key: Name
                  Value: Subnet1
    
    MyVPCSubnet2:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref MyVPC
            CidrBlock: 10.0.3.16/28
            AvailabilityZone: !Select [ 1, !GetAZs '' ]
            MapPublicIpOnLaunch: true
            Tags:
                - Key: Name
                  Value: Subnet2

    MyRouteTable:
        Type: AWS::EC2::RouteTable
        Properties:
            VpcId: !Ref MyVPC 
            Tags: 
                - Key: Name
                  Value: MyRouteTable

    MyInternetRoute:
        Type: AWS::EC2::Route
        Properties:
            RouteTableId: !Ref MyRouteTable
            DestinationCidrBlock: 0.0.0.0/0
            GatewayId: !Ref MyInternetGateway


    MySubnetAssociation1:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref MyRouteTable
            SubnetId: !Ref MyVPCSubnet1

    MySubnetAssociation2:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref MyRouteTable
            SubnetId: !Ref MyVPCSubnet2


    MyLbSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allow HTTP and HTTPS from everywhere
            VpcId: !Ref MyVPC
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 80
                  ToPort: 80
                  CidrIp: 0.0.0.0/0
                - IpProtocol: tcp
                  FromPort: 443
                  ToPort: 443
                  CidrIp: 0.0.0.0/0
                  
                      
    MyServerSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allow HTTP and HTTPS from Load Balancer
            VpcId: !Ref MyVPC
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 80
                  ToPort: 80
                  SourceSecurityGroupId: !Ref MyLbSecurityGroup
                
                - IpProtocol: tcp
                  FromPort: 443
                  ToPort: 443
                  SourceSecurityGroupId: !Ref MyLbSecurityGroup



    
    MyS3Bucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketEncryption:
                ServerSideEncryptionConfiguration:
                    - ServerSideEncryptionByDefault:
                        SSEAlgorithm: AES256
            PublicAccessBlockConfiguration:
                BlockPublicAcls: true
                BlockPublicPolicy: true
                IgnorePublicAcls: true
                RestrictPublicBuckets: true
            

    MyVulnerableRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                        Service: "ec2.amazonaws.com"
                      Action: 'sts:AssumeRole'
            Policies:
                - PolicyName: S3policy
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                        - Effect: Allow
                          Action:
                            - s3:GetObject
                            - s3:ListBucket
                          Resource: 
                            - !GetAtt MyS3Bucket.Arn
                            - !Sub ${MyS3Bucket.Arn}/*


    MyInstanceProfile:
        Type: AWS::IAM::InstanceProfile
        Properties:
            Roles:
                - !Ref MyVulnerableRole


    
    MyinstanceTargetgroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            Port: 80
            Protocol: HTTP
            VpcId: !Ref MyVPC
            TargetType: instance
            HealthCheckPath: /
    
    MyLoadBalancer:
        Type: AWS::ElasticLoadBalancingV2::LoadBalancer
        Properties:
            Scheme: internet-facing
            Subnets:
                - !Ref MyVPCSubnet1
                - !Ref MyVPCSubnet2
            SecurityGroups: 
                - !Ref MyLbSecurityGroup

    MyListener:
        Type: AWS::ElasticLoadBalancingV2::Listener
        Properties:
            LoadBalancerArn: !Ref MyLoadBalancer
            DefaultActions: 
                - Type: forward
                  TargetGroupArn: !Ref MyinstanceTargetgroup
            Port: 80
            Protocol: HTTP

    MyLaunchTemplate:
        Type: AWS::EC2::LaunchTemplate
        Properties:
            LaunchTemplateName: MyJuiceShop-template
            LaunchTemplateData:
                ImageId:  resolve:ssm:/aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id
                InstanceType: !Ref InstanceType
                KeyName: !Ref KeyName
                SecurityGroupIds:
                    - !Ref MyServerSecurityGroup
                IamInstanceProfile: 
                    Name: !Ref MyInstanceProfile
                UserData: 
                    Fn::Base64: !Sub | 
                        #!/bin/bash
                        # Update and install Docker
                        apt-get update -y
                        apt-get install -y docker.io
                        
                        # Start Docker service
                        systemctl start docker
                        systemctl enable docker
                        
                        # Pull and run the Juice Shop container
                        # Maps Host Port 80 -> Container Port 3000
                        docker run -d -p 80:3000 --restart always --name juice-shop bkimminich/juice-shop


    MyAutoScalingGroup:
        Type: AWS::AutoScaling::AutoScalingGroup
        Properties:
            MinSize: 1
            MaxSize: 3
            LaunchTemplate: 
                LaunchTemplateId: !Ref MyLaunchTemplate
                Version: !GetAtt MyLaunchTemplate.LatestVersionNumber
            HealthCheckType: ELB
            HealthCheckGracePeriod: 300
            TargetGroupARNs:
                - !Ref MyinstanceTargetgroup
            VPCZoneIdentifier:
                - !Ref MyVPCSubnet1
                - !Ref MyVPCSubnet2





Outputs:
    LoadBalancerDNS:
        Description: the URL of the Load Balancer
        Value: !GetAtt MyLoadBalancer.DNSName

